/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class ApplePayRequestBuilder {
    //the instance to build
    private ApplePayRequest applePayRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApplePayRequestBuilder() {
        applePayRequest = new ApplePayRequest();
    }

    /**
     * The token version
     */
    public ApplePayRequestBuilder version(String version) {
        applePayRequest.setVersion(version);
        return this;
    }

    /**
     * The cryptography data
     */
    public ApplePayRequestBuilder data(String data) {
        applePayRequest.setData(data);
        return this;
    }

    /**
     * The apple pay header request
     */
    public ApplePayRequestBuilder header(ApplePayHeaderRequest header) {
        applePayRequest.setHeader(header);
        return this;
    }

    /**
     * Detached PKCS #7 signature, Base64 encoded as string
     */
    public ApplePayRequestBuilder signature(String signature) {
        applePayRequest.setSignature(signature);
        return this;
    }

    /**
     * ApplePay Merchant identifier
     */
    public ApplePayRequestBuilder merchantIdentifier(String merchantIdentifier) {
        applePayRequest.setMerchantIdentifier(merchantIdentifier);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApplePayRequest build() {
        return applePayRequest;
    }
}