/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class ClearSaleRequestBuilder {
    //the instance to build
    private ClearSaleRequest clearSaleRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ClearSaleRequestBuilder() {
        clearSaleRequest = new ClearSaleRequest();
    }

    public ClearSaleRequestBuilder customSla(int customSla) {
        clearSaleRequest.setCustomSla(customSla);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ClearSaleRequest build() {
        return clearSaleRequest;
    }
}