/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateCardPaymentTokenRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6949900181091978407L;
    private String type;
    private CreateApplePayRequest applePay;
    private CreateGooglePayRequest googlePay;
    /** GETTER
     * The authentication type
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The authentication type
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * The ApplePay authentication request
     */
    @JsonGetter("apple_pay")
    public CreateApplePayRequest getApplePay ( ) { 
        return this.applePay;
    }
    
    /** SETTER
     * The ApplePay authentication request
     */
    @JsonSetter("apple_pay")
    public void setApplePay (CreateApplePayRequest value) { 
        this.applePay = value;
    }
 
    /** GETTER
     * The GooglePay authentication request
     */
    @JsonGetter("google_pay")
    public CreateGooglePayRequest getGooglePay ( ) { 
        return this.googlePay;
    }
    
    /** SETTER
     * The GooglePay authentication request
     */
    @JsonSetter("google_pay")
    public void setGooglePay (CreateGooglePayRequest value) { 
        this.googlePay = value;
    }
 
}
