/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateCashPaymentRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5695479658345017447L;
    private String description;
    private boolean confirm;
    /** GETTER
     * Description
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * Description
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * Indicates whether cash collection will be confirmed in the act of creation
     */
    @JsonGetter("confirm")
    public boolean getConfirm ( ) { 
        return this.confirm;
    }
    
    /** SETTER
     * Indicates whether cash collection will be confirmed in the act of creation
     */
    @JsonSetter("confirm")
    public void setConfirm (boolean value) { 
        this.confirm = value;
    }
 
}
 