/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CreateCardPaymentTokenRequestBuilder {
    //the instance to build
    private CreateCardPaymentTokenRequest createCardPaymentTokenRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateCardPaymentTokenRequestBuilder() {
        createCardPaymentTokenRequest = new CreateCardPaymentTokenRequest();
    }

    /**
     * The authentication type
     */
    public CreateCardPaymentTokenRequestBuilder type(String type) {
        createCardPaymentTokenRequest.setType(type);
        return this;
    }

    /**
     * The ApplePay authentication request
     */
    public CreateCardPaymentTokenRequestBuilder applePay(CreateApplePayRequest applePay) {
        createCardPaymentTokenRequest.setApplePay(applePay);
        return this;
    }

    /**
     * The GooglePay authentication request
     */
    public CreateCardPaymentTokenRequestBuilder googlePay(CreateGooglePayRequest googlePay) {
        createCardPaymentTokenRequest.setGooglePay(googlePay);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateCardPaymentTokenRequest build() {
        return createCardPaymentTokenRequest;
    }
}