/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class GetUsageReportResponseBuilder {
    //the instance to build
    private GetUsageReportResponse getUsageReportResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetUsageReportResponseBuilder() {
        getUsageReportResponse = new GetUsageReportResponse();
    }

    public GetUsageReportResponseBuilder url(String url) {
        getUsageReportResponse.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetUsageReportResponse build() {
        return getUsageReportResponse;
    }
}