/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class UpdateSubscriptionStartDateRequestBuilder {
    //the instance to build
    private UpdateSubscriptionStartDateRequest updateSubscriptionStartDateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSubscriptionStartDateRequestBuilder() {
        updateSubscriptionStartDateRequest = new UpdateSubscriptionStartDateRequest();
    }

    /**
     * The date when the subscription periods will start
     */
    public UpdateSubscriptionStartDateRequestBuilder startAt(DateTime startAt) {
        updateSubscriptionStartDateRequest.setStartAt(startAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSubscriptionStartDateRequest build() {
        return updateSubscriptionStartDateRequest;
    }
}