/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mundipagg.api.DateTimeHelper;
import org.joda.time.DateTime;

public class UpdateCurrentCycleEndDateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -123069070857612039L;
    private DateTime endAt;
    /** GETTER
     * Current cycle end date
     */
    @JsonGetter("end_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getEndAt ( ) { 
        return this.endAt;
    }
    
    /** SETTER
     * Current cycle end date
     */
    @JsonSetter("end_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setEndAt (DateTime value) { 
        this.endAt = value;
    }
 
}
 